import { getAuthenticatedUser } from "./_lib/auth.js";

const page = `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>Entrar · New Order</title>
<style>:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#18222c;background:#f6f7f4}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:20px}.card{width:min(100%,430px);background:#fff;border:1px solid #e5eae6;border-radius:22px;padding:32px;box-shadow:0 16px 44px #17222c18}.mark{display:grid;place-items:center;width:48px;height:48px;background:#17222c;color:#ffd734;border-radius:14px;font-size:22px;font-weight:900}.eyebrow{display:block;color:#a57f00;font-size:11px;font-weight:900;letter-spacing:.13em;margin:23px 0 8px}h1{font-size:29px;letter-spacing:-.05em;margin:0 0 7px}p{font-size:14px;line-height:1.55;color:#617078;margin:0 0 24px}label{display:block;font-size:12px;font-weight:800;margin:15px 0 6px}input{width:100%;border:1px solid #dce3df;border-radius:11px;padding:12px;color:#18222c;font:inherit}input:focus{outline:3px solid #ffd73488;border-color:#c59200}button{width:100%;border:0;border-radius:11px;background:#18222c;color:#fff;padding:13px 16px;font:inherit;font-weight:800;margin-top:22px;cursor:pointer}button:hover{background:#33424b}button:disabled{opacity:.65;cursor:wait}.error{min-height:20px;color:#ad3428;font-size:13px;margin:13px 0 0}.help{font-size:11px;color:#74838a;margin-top:20px}</style></head>
<body><main class="card"><div class="mark">N.</div><span class="eyebrow">NEW ORDER · ACESSO RESTRITO</span><h1>Entrar no playbook</h1><p>Use o e-mail e a senha fornecidos pela administração.</p><form id="loginForm"><label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="email" required autofocus><label for="password">Senha</label><input id="password" name="password" type="password" autocomplete="current-password" required><button id="submit" type="submit">Entrar</button><p class="error" id="error" role="alert" aria-live="polite"></p></form><p class="help">Não há cadastro público. Fale com a administração se precisar de acesso.</p></main><script>const form=document.querySelector('#loginForm'),button=document.querySelector('#submit'),error=document.querySelector('#error');form.addEventListener('submit',async(event)=>{event.preventDefault();error.textContent='';button.disabled=true;button.textContent='Entrando…';try{const response=await fetch('/api/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.email.value,password:form.password.value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível entrar.');location.assign('/')}catch(reason){error.textContent=reason.message||'Não foi possível entrar.';button.disabled=false;button.textContent='Entrar'}});</script></body></html>`;

export async function onRequestGet(context) {
  try {
    if (await getAuthenticatedUser(context.request, context.env)) return Response.redirect(new URL("/", context.request.url), 302);
  } catch (error) {
    console.error("Login configuration error", error);
  }
  return new Response(page, { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });
}
